### ISSUE TITLE
740H20140423 - potential cf issues?

### ISSUE THREAD

**Issue by eaitoro** [cchdo/hydro#30]
link: [https://cchdo.ucsd.edu/cruise/740H20140423](https://cchdo.ucsd.edu/cruise/740H20140423)

zip file: [740H20140423.zip](https://github.com/cchdo/hydro/files/10551950/740H20140423.zip)
- contains the nc file I downloaded from cchdo.ucsd.edu, the exchange file, and another nc file that I made on my own machine (out.nc)

**Comment by DocOtak** [comment]
Specifically, something is wrong with the cast variable that @eaitoro occasionally sees ncdump crash on. She reports this is with both the online file, and one she made herself.

**Comment by DocOtak** [comment]
Some good news, this is purely an issue with the `"C_format"` attribute and ncdump trying to print the integer dtype with a floating point format string. The underlying data in the netCDF files accurately reflects the input data.

I think the fix will be to remove the C_format attrs from anything that is not a floating point type variable (either single or double).

**Comment by DocOtak** [comment]
Fixed in 5979628eae07817f75c3d796e65df5e8715be4f5
